# Generated by Django 5.1 on 2024-09-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CaloricDuration',
            fields=[
                ('baseduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.baseduration')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Calories'), (2, 'Kilocalories')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workouts.baseduration',),
        ),
        migrations.CreateModel(
            name='DistanceDuration',
            fields=[
                ('baseduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.baseduration')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Miles'), (2, 'Kilometers'), (3, 'Meters')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workouts.baseduration',),
        ),
        migrations.CreateModel(
            name='HeartRateDuration',
            fields=[
                ('baseduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.baseduration')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Beats Per Minute'), (2, 'Percentage')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workouts.baseduration',),
        ),
        migrations.CreateModel(
            name='PowerDuration',
            fields=[
                ('baseduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.baseduration')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Watts'), (2, 'Kilowatts')], default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workouts.baseduration',),
        ),
        migrations.CreateModel(
            name='TimeDuration',
            fields=[
                ('baseduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workouts.baseduration')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'Seconds'), (2, 'Minutes'), (3, 'Hours')], default=2)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('workouts.baseduration',),
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Warm-up'), (2, 'Cool-down'), (3, 'Active'), (4, 'Rest')], default=3)),
                ('perceived_effort', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], null=True)),
                ('parent', models.PositiveIntegerField(blank=True, help_text='This will serve as a pointer to the parent intervals PK.', null=True)),
                ('repititions', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='workouts.baseduration')),
                ('rest_interval', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeat_interval', to='workouts.interval')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('workout_type', models.PositiveSmallIntegerField(choices=[(1, 'Run'), (2, 'Swim'), (3, 'Cycle')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('intervals', models.ManyToManyField(related_name='workouts', to='workouts.interval')),
            ],
        ),
    ]
