# Generated by Django 5.1 on 2024-08-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinterval',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='baseinterval',
            name='order',
        ),
        migrations.AddField(
            model_name='baseinterval',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_interval', to='workouts.baseinterval'),
        ),
    ]
