# Generated by Django 5.1 on 2024-08-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_baseinterval_options_remove_baseinterval_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinterval',
            name='next',
        ),
        migrations.AddField(
            model_name='baseinterval',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_interval', to='workouts.baseinterval'),
        ),
    ]
