# Generated by Django 5.1 on 2024-08-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_baseinterval_next_baseinterval_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='components',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='cooldown',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='warmup',
        ),
        migrations.AddField(
            model_name='workout',
            name='first_interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_first_interval', to='workouts.interval'),
        ),
        migrations.AddField(
            model_name='workout',
            name='last_interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_last_interval', to='workouts.interval'),
        ),
    ]
